### ISSUE TITLE
Modify Course model to store a list of reviews

### ISSUE THREAD

**Issue by DylanApardian** [ApplETS/ETS-API-Clients#35]
## Description

As part of https://github.com/ApplETS/Notre-Dame/issues/941, the `Course` model needs to be changed to allow a course to have multiple reviews.

In short, there are cases where some courses have multiple teachers. 
During the course evaluation period, we want to display `N/A` as the course's grade until the student has completed ALL course reviews for that course. 

Currently we're only storing 1 review. Because of this, if a course has multiple teachers, and we only evaluate 1 teacher, the mobile app is displaying `0%` as the grade instead of `N/A`

## Implementation Details

Instead of `CourseReview? review` we should have something like `List<CourseReview>? review`

**Comment by MysticFragilist** [comment]
Ici j'imagine faut close? @DylanApardian

**Comment by MysticFragilist** [comment]
Oups j'ai close sans faire exprès 😅 feel free de réouvrir si c'est pas le cas!

**Comment by DylanApardian** [comment]
> Oups j'ai close sans faire exprès 😅 feel free de réouvrir si c'est pas le cas!

Oui, il fallait close. J'avais oublié. Thanks
